DROP DATABASE IF EXISTS game 

CREATE DATABASE game

CREATE TABLE game_score (
    game_id int(10) PRIMARY KEY AUTO_INCREMENT,
    player_time NOT_NULL DEFAULT CURRENT_TIMESTAMP, 
    score_comment VARCHAR(100) DEFAULT NULL, 
    ) ENGINE=INNODB DEFAULT CHARSET=UTF8;
